name: Verify Build

on:
  push:
    branches: [ main, citest ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate_versions:
    name: Generate versionsk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: setup-matrix
        run: echo "matrix=$(jq -cM '.supportedVersions | keys' src/main/resources/versions.json | sed -e 's/\./_/g' -e 's/-/_/g')" >> $GITHUB_OUTPUT
      - name: debug
        run: echo ${{ steps.setup-matrix.outputs.matrix }}
      - id: setup-matrix-java-17
        run: echo "matrix=$(jq -cM '.supportedVersions | keys' src/main/resources/versions_java17.json | sed -e 's/\./_/g' -e 's/-/_/g')" >> $GITHUB_OUTPUT
      - name: debug java 17
        run: echo ${{ steps.setup-matrix.outputs.matrix-java17 }}
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}
      matrix-java17: ${{ steps.setup-matrix.outputs.matrix-java17 }}
