name: Verify Build2

on:
  push:
    branches: [ main, citest ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate_versions:
    name: Generate versionsk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: setup-matrix
        run: echo "matrix=$(jq -cM '.supportedVersions | keys' src/main/resources/versions.json | sed -e 's/\./_/g' -e 's/-/_/g')" >> $GITHUB_OUTPUT
      - name: debug
        run: echo ${{ steps.setup-matrix.outputs.matrix }}
      - id: setup-matrix-java-17
        run: echo "matrix=$(jq -cM '.supportedVersions | keys' src/main/resources/versions_java17.json | sed -e 's/\./_/g' -e 's/-/_/g')" >> $GITHUB_OUTPUT
      - name: debug java 17
        run: echo ${{ steps.setup-matrix-java-17.outputs.matrix }}
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}
      matrix-java17: ${{ steps.setup-matrix-java-17.outputs.matrix }}



  android_version_tests_java_17:
    name: Android version tests Java 17
    needs: [ generate_versions ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        versions: ${{ fromJson(needs.generate_versions.outputs.matrix-java17) }}
    steps:
      - uses: actions/checkout@v3
      # Patch issue in platform-tools 31.0.3 where platform-tools/api/api-versions.xml is missing (see https://issuetracker.google.com/issues/195445762)
      - name: Patch api-versions
        run: sudo test -f $ANDROID_HOME/platform-tools/api/api-versions.xml || (sudo mkdir $ANDROID_HOME/platform-tools/api && sudo cp .github/api-versions.xml $ANDROID_HOME/platform-tools/api/api-versions.xml)
      - name: List Android Packages
        run: sudo $ANDROID_HOME/tools/bin/sdkmanager --list | sed -n '/Available Packages/q;p'
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Run integration tests Java 17
        run: ./gradlew testAndroid${{ matrix.versions }} -x signPluginMavenPublication -x signAndroidCacheFixPluginPluginMarkerMavenPublication
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
